language: r
# Allow for sudo commands, because we need Tcl and the containerised version
# on Travis CI does not provide it!
sudo: required

os:
  - linux
  - osx

branches:
  only:
    - master
    - macosx

# On Linux, there is warning complaining for missing DISPLAY, so that Tk
# is not available... but we don't need Tk, only Tcl here => ignore warnings
warnings_are_errors: false
# Note: can also add --no-build-vignettes to both
r_build_args: --no-manual --no-resave-data
r_check_args: --no-manual

# Email notifications
notifications:
  email:
    on_success: change
    on_failure: change
     
# Environment variables
env:
 global:
   - CRAN: http://cran.rstudio.com

# System dependencies
#apt_packages:
# - libcurl4-openssl-dev
# - libxml2-dev
# Binary R packages (faster, but not always latest versions!)
r_binary_packages:
  - svMisc
  # For covr
  - jsonlite  
  - devtools
  - httr
  - crayon
  - htmltools
  - knitr
  #- rex # Fails to compile for precise in Rutter's PPA
  # For rex
  - magrittr
  - lazyeval
  # For tests
  - svUnit

# R package to be compiled from sources (latest versions!)
r_packages:
  - rex
  - covr
  - svHttp

# Bioconductor packages
#bioc_packages:

# Install the bleeding edge version of a package from github (eg to pick
# up a not-yet-released bugfix)
#r_github_packages:
# - jimhester/covr

# Install additional stuff
#before_install:
#  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#  - sudo apt-get update -qq
#  - sudo apt-get install -qq <packages>
#  - sudo apt-get install -qq g++-4.8
#  - export CXX="g++-4.8"
#  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
#  - sudo ln -s /usr/lib/x86_64-linux-gnu/libgfortran.so.3 /usr/lib/libgfortran.so
 
after_success:
  - Rscript -e 'covr::codecov()'
